name: Setup Project
description: Setup the project for development
runs:
  using: 'composite'
  steps:
    - uses: jdx/mise-action@v3
    - name: Cache go modules
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/go-build
          ~/.cache/go-mod
        key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('go.mod') }}
    - name: Cache Bun dependencies
      uses: actions/cache@v5
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-bun-${{ hashFiles('bun.lockb', 'package.json') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    - name: Install Fyne build dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev pkg-config
    - name: Install dependencies
      shell: bash
      run: mise run install
